module.exports = {
  extends: ['@commitlint/config-conventional'],
  // Skip linting commits generated by automated tooling whose bodies legitimately
  // exceed our normal length rules (semantic-release's chore(release): ...
  // commit embeds the full changelog; dependabot may use long footers).
  ignores: [
    (message) => /^chore\(release\): /.test(message),
    (message) => /^Signed-off-by: dependabot\[bot\]/.test(message),
  ],
};
