module.exports = {
  extends: ['@commitlint/config-conventional'],
  // Skip linting commits generated by automated tooling whose bodies legitimately
  // exceed our normal length rules (semantic-release's chore(release): ...
  // commit embeds the full changelog; dependabot may use long footers).
  ignores: [
    (message) => /^chore\(release\): /.test(message),
    // `Signed-off-by` is a footer line, not the first line, so don't anchor
    // to `^`; match anywhere in the commit message.
    (message) => /Signed-off-by: dependabot\[bot\]/.test(message),
  ],
  // GitHub's squash-merge builds each commit body by concatenating the
  // feature branch's commit messages, which routinely exceeds 100 columns.
  // That squashed body is never linted pre-merge: the feature->next PR lints
  // the pre-squash branch commits, not the resulting squash commit. The long
  // lines only surface at `next`->`main` promotion time, where this workflow
  // re-lints the whole range. Body/footer wrapping carries no semantic-release
  // signal (only the header type does), so don't gate promotion on it.
  rules: {
    'body-max-line-length': [0, 'always', 100],
    'footer-max-line-length': [0, 'always', 100],
  },
};
