name: Build Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
      types: [opened, reopened, synchronize, review_requested]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
    #   uses: actions/setup-node@v3.8.1
    
    # - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Docker setup `buildx`
      # You may pin to the exact commit or the version.
      # uses: docker/setup-buildx-action@4c0219f9ac95b02789c1075625400b2acbff50b1
      uses: docker/setup-buildx-action@v2.9.1

    - name: Get Package Version
      run: VERSION=$(jq -r '.version' package.json) && echo "Package version is $VERSION"
    
    - name: Set DEV tag
      if: github.event_name != "push"
      run: TAG=dev && echo "Tag is $TAG"

    - name: Set LATEST tag
      if: github.event_name == "push"
      run: TAG=latest && echo "Tag is $TAG"

    - name: Build and publish Docker image
      if: github.event_name == "push"
      run: docker buildx build --push --platform linux/amd64 --tag hawkeyexl/verbagpt:${{ env.VERSION }} --tag hawkeyexl/verbagpt:${{ env.TAG }} .
      # TODO: Update to include linux/arm64 platform when browser downloading supports it
      # run: docker buildx build --push --platform linux/amd64,linux/arm64 --tag hawkeyexl/verbagpt:latest .
