name: Build Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
      types: [opened, reopened, synchronize, review_requested]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
    #   uses: actions/setup-node@v3.8.1
    
    # - name: Docker login
    #   run: docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}
    
    - name: Docker setup `buildx`
      # You may pin to the exact commit or the version.
      # uses: docker/setup-buildx-action@4c0219f9ac95b02789c1075625400b2acbff50b1
      uses: docker/setup-buildx-action@v2.9.1
    # - name: Build the Docker image
    #   run: npm run docker:build:multiarch

    - name: Build the Docker image
      if: github.event_name !== "push"
      run: docker buildx build --platform linux/amd64 --tag hawkeyexl/verbagpt:latest .
      # TODO: Update to include linux/arm64 platform when browser downloading supports it
      # run: docker buildx build --platform linux/amd64,linux/arm64 --tag hawkeyexl/verbagpt:latest .

    - name: Build and publish the Docker image
      if: github.event_name === "push"
      run: docker buildx build --push --platform linux/amd64 --tag hawkeyexl/verbagpt:latest .
      # TODO: Update to include linux/arm64 platform when browser downloading supports it
      # run: docker buildx build --push --platform linux/amd64,linux/arm64 --tag hawkeyexl/verbagpt:latest .
