name: Build and publish Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
      types: [opened, reopened, synchronize, review_requested]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker setup `buildx`
      uses: docker/setup-buildx-action@v2.9.1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Get package version
      run: echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV
    
    - name: Set DEV tag
      if: github.event_name != 'push'
      run: echo "TAG=dev" >> $GITHUB_ENV

    - name: Set LATEST tag
      if: github.event_name == 'push'
      run: echo "TAG=latest" >> $GITHUB_ENV

    - name: Docker login
      run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Build and publish Docker image
      run: docker buildx build --push --platform linux/amd64 --tag hawkeyexl/doc-detective:${{ env.VERSION }} --tag hawkeyexl/doc-detective:${{ env.TAG }} --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache .
      
      # TODO: Update to include linux/arm64 platform when browser downloading supports it
      # run: docker buildx build --push --platform linux/amd64,linux/arm64 --tag hawkeyexl/verbagpt:latest .
