name: Build and publish Electron bundles

on:
  push:
    branches: [ "main" ]
  pull_request:
      types: [opened, reopened, synchronize, review_requested]
  workflow_dispatch:


jobs:
  publish:
    name: Build and Publish Electron bundle
    permissions: write-all
    runs-on: macos-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      
      - name: Set up Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: cd electron && npm i
      
      - name: Build Electron bundles
        run: cd electron && npm run build -- -mw --x64 --arm64 --publish always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload Multiple Release Assets
      #   uses: NBTX/upload-release-assets@v1
      #   with:
      #     # The URL for uploading assets to the release
      #     upload_url: ${{ env.UPLOAD_URL }} || ${{ github.event.release.upload_url }}
      #     # A glob of assets to upload
      #     targets: ./electron/dist/*.{exe,dmg,zip}
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
