name: Build and publish Electron bundles

on:
  release:
    types: [created,edited,prereleased,published]
  workflow_dispatch:


jobs:
  publish:
    name: Build and Publish Electron bundle (macOS)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          # - ubuntu-latest
          - macos-latest
          # - windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      
      - name: Set up Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: cd electron && npm i
      
      - name: Build Electron bundles
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            cd electron && npm run build -- --x64 --arm64
          elif [ "$RUNNER_OS" == "Windows" ]; then
            cd electron && npm run build -- --x64
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
