name: Build and publish Electron bundles

on:
  push:
    branches: [ "main" ]
  pull_request:
      types: [opened, reopened, synchronize, review_requested]
  workflow_dispatch:

env:
  PUBLISH_FOR_PULL_REQUEST: true

jobs:
  publish:
    name: Build and Publish Electron bundle
    permissions: write-all
    runs-on: macos-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      
      - name: Set up Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: cd electron && npm i
      
      - name: Build Electron bundles (macOS)
        run: cd electron && npm run build -- -m --x64 --arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Electron bundles (Windows)
        run: cd electron && npm run build -- -w -x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Electron bundles (Linux)
        run: cd electron && npm run build -- -l --x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
