name: Publish Electron bundles

on:
  release:
    types: [created,edited,prereleased,published]

jobs:
  publish:
    name: Build and Publish Electron bundle
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: cd electron && npm i
      - name: Build Electron bundles
        run: cd electron && npm run build
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        with:
          name: Election bundles
          path: ./electron/dist/Doc Detective.*(\.exe|\.zip|\.dmg)$
          url: ${{ github.event.release.upload_url }}
          token: ${{ secrets.GITHUB_TOKEN }}