name: Update doc-detective-core version

on:
  repository_dispatch:
    types:
      - update-core-package-event
  workflow_dispatch:
    inputs:
      version:
        description: 'The doc-detective-core version.'
        required: false
        default: 'latest'

jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.DD_DEP_UPDATE_TOKEN }}

    - name: Set version variable
      id: version
      run: |
        VERSION="${{ github.event.client_payload.version || github.event.inputs.version || 'latest' }}"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Using version: $VERSION"

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Get version of doc-detective-common from core
      id: common_version
      run: |
        COMMON_VERSION=$(npm view doc-detective-core@${{ steps.version.outputs.version }} dependencies --json | jq -r '.["doc-detective-common"]')
        echo "common_version=$COMMON_VERSION" >> $GITHUB_OUTPUT

    - name: Install specific versions of doc-detective-core and doc-detective-common
      run: |
        npm install doc-detective-core@${{ steps.version.outputs.version }} doc-detective-common@${{ steps.common_version.outputs.common_version }} || {
          echo "Failed to install doc-detective-core@${{ steps.version.outputs.version }} or doc-detective-common@${{ steps.common_version.outputs.common_version }}"
          exit 1
        }
          npm audit fix
    
    - name: Test the installation
      run: |
        npm test
    
    - name: Commit changes
      id: commit
      run: |
        git add package.json package-lock.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          git commit -m "bump doc-detective-core version to ${{ steps.version.outputs.version }} [skip ci]"
          git push
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Bump or sync version
      id: patch
      if: steps.commit.outputs.has_changes == 'true'
      run: |
        git checkout -- .
        git clean -fd
        # Get current project version
        PROJ_VERSION=$(node -p "require('./package.json').version")
        # Get doc-detective-core version (strip ^ or ~)
        CORE_VERSION=$(node -p 'require("./package.json").dependencies?.["doc-detective-core"] || require("./package.json").devDependencies?.["doc-detective-core"] || ""')
        CORE_VERSION=$(echo "$CORE_VERSION" | sed 's/^[^0-9]*//')
        # Parse versions
        PROJ_MAJOR=$(echo $PROJ_VERSION | cut -d. -f1)
        PROJ_MINOR=$(echo $PROJ_VERSION | cut -d. -f2)
        CORE_MAJOR=$(echo $CORE_VERSION | cut -d. -f1)
        CORE_MINOR=$(echo $CORE_VERSION | cut -d. -f2)
        if [ "$PROJ_MAJOR" != "$CORE_MAJOR" ] || [ "$PROJ_MINOR" != "$CORE_MINOR" ]; then
          # Major or minor mismatch: set version to match doc-detective-core major.minor.0
          NEW_VERSION="$CORE_MAJOR.$CORE_MINOR.0"
          npm version --no-git-tag-version "$NEW_VERSION"
        else
          # Only patch changed: bump patch
          npm version patch --no-git-tag-version
        fi
        git add package.json package-lock.json
        git commit -m "bump version to match doc-detective-core [skip ci]"
        git push
        git tag "v$(node -p \"require('./package.json').version\")"
        git push --tags
        echo "version=$(node -p \"require('./package.json').version\")" >> $GITHUB_OUTPUT

    - name: Create release
      if: steps.commit.outputs.has_changes == 'true'
      # Install GitHub CLI for fetching PRs and release notes
      run: |
        sudo apt-get update && sudo apt-get install -y gh jq

    - name: Gather merged PRs since last release
      id: merged_prs
      run: |
        # Get previous tag (before the new one)
        PREV_TAG=$(git tag --sort=-creatordate | grep -v "v${{ steps.patch.outputs.version }}" | head -n1)
        CURR_TAG="v${{ steps.patch.outputs.version }}"
        echo "Previous tag: $PREV_TAG, Current tag: $CURR_TAG"
        if [ -z "$PREV_TAG" ]; then
          echo "No previous tag found. Skipping PR list."
          echo "prs=No previous release found." >> $GITHUB_OUTPUT
        else
          PRS=$(gh pr list --state merged --search "merged:>=$(git log -1 --format=%aI $PREV_TAG)" --json number,title,url --jq '.[] | "- [#\(.number)](\(.url)): \(.title)"')
          if [ -z "$PRS" ]; then
            PRS=""
          fi
          echo "prs<<EOF" >> $GITHUB_OUTPUT
          echo "$PRS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        fi

    - name: Fetch doc-detective-core release notes
      id: CORE_release
      run: |
        CORE_VERSION=${{ steps.version.outputs.version }}
        # Remove ^ or ~ if present
        CORE_VERSION_CLEAN=$(echo "$CORE_VERSION" | sed 's/^[^0-9]*//')
        # Query GitHub API for release notes
        RELEASE_INFO=$(gh release view "v$CORE_VERSION_CLEAN" --repo doc-detective/doc-detective-core --json body --jq .body || echo "No release notes found.")
        echo "release_notes<<EOF" >> $GITHUB_OUTPUT
        echo "$RELEASE_INFO" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create release with detailed notes
      if: steps.commit.outputs.has_changes == 'true'
      uses: softprops/action-gh-release@v2
      with:
        body: |
          # What's new

          - Updated doc-detective-core to v${{ steps.patch.outputs.version }}:

            ${{ steps.CORE_release.outputs.release_notes }}

          ${{ steps.merged_prs.outputs.prs }}
        tag_name: "v${{ steps.patch.outputs.version }}"
        name: "v${{ steps.patch.outputs.version }}"
        generate_release_notes: false
        token: ${{ secrets.DD_DEP_UPDATE_TOKEN }}

